/*
 * This file is generated by jOOQ.
 */
package com.quick.quickmodel.dao.tables;


import com.quick.quickmodel.dao.Indexes;
import com.quick.quickmodel.dao.Keys;
import com.quick.quickmodel.dao.Knowledgemap;
import com.quick.quickmodel.dao.tables.records.KnowledgeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Knowledge extends TableImpl<KnowledgeRecord> {

    private static final long serialVersionUID = 506694854;

    /**
     * The reference instance of <code>knowledgemap.knowledge</code>
     */
    public static final Knowledge KNOWLEDGE = new Knowledge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KnowledgeRecord> getRecordType() {
        return KnowledgeRecord.class;
    }

    /**
     * The column <code>knowledgemap.knowledge.id</code>.
     */
    public final TableField<KnowledgeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>knowledgemap.knowledge.name</code>.
     */
    public final TableField<KnowledgeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<KnowledgeRecord, Object> PROPERTY = createField("property", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"knowledge_property\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<KnowledgeRecord, Object> KNOWLEDGE_RELATION = createField("knowledge_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"knowledge_knowledge_relation\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<KnowledgeRecord, Object> OBJECT_RELATION = createField("object_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"knowledge_object_relation\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<KnowledgeRecord, Object> DOC_RELATION = createField("doc_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"knowledge_doc_relation\""), this, "");

    /**
     * Create a <code>knowledgemap.knowledge</code> table reference
     */
    public Knowledge() {
        this(DSL.name("knowledge"), null);
    }

    /**
     * Create an aliased <code>knowledgemap.knowledge</code> table reference
     */
    public Knowledge(String alias) {
        this(DSL.name(alias), KNOWLEDGE);
    }

    /**
     * Create an aliased <code>knowledgemap.knowledge</code> table reference
     */
    public Knowledge(Name alias) {
        this(alias, KNOWLEDGE);
    }

    private Knowledge(Name alias, Table<KnowledgeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Knowledge(Name alias, Table<KnowledgeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Knowledge(Table<O> child, ForeignKey<O, KnowledgeRecord> key) {
        super(child, key, KNOWLEDGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Knowledgemap.KNOWLEDGEMAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.KNOWLEDGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<KnowledgeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_KNOWLEDGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KnowledgeRecord> getPrimaryKey() {
        return Keys.KEY_KNOWLEDGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KnowledgeRecord>> getKeys() {
        return Arrays.<UniqueKey<KnowledgeRecord>>asList(Keys.KEY_KNOWLEDGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Knowledge as(String alias) {
        return new Knowledge(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Knowledge as(Name alias) {
        return new Knowledge(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Knowledge rename(String name) {
        return new Knowledge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Knowledge rename(Name name) {
        return new Knowledge(name, null);
    }
}
