/*
 * This file is generated by jOOQ.
 */
package com.quick.quickmodel.dao.tables;


import com.quick.quickmodel.dao.Indexes;
import com.quick.quickmodel.dao.Keys;
import com.quick.quickmodel.dao.Knowledgemap;
import com.quick.quickmodel.dao.tables.records.ObRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ob extends TableImpl<ObRecord> {

    private static final long serialVersionUID = 957674503;

    /**
     * The reference instance of <code>knowledgemap.ob</code>
     */
    public static final Ob OB = new Ob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ObRecord> getRecordType() {
        return ObRecord.class;
    }

    /**
     * The column <code>knowledgemap.ob.id</code>.
     */
    public final TableField<ObRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>knowledgemap.ob.name</code>.
     */
    public final TableField<ObRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<ObRecord, Object> PROPERTY = createField("property", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"ob_property\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<ObRecord, Object> KNOWLEDGE_RELATION = createField("knowledge_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"ob_knowledge_relation\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<ObRecord, Object> OBJECT_RELATION = createField("object_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"ob_object_relation\""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<ObRecord, Object> DOC_RELATION = createField("doc_relation", org.jooq.impl.DefaultDataType.getDefaultDataType("\"knowledgemap\".\"ob_doc_relation\""), this, "");

    /**
     * Create a <code>knowledgemap.ob</code> table reference
     */
    public Ob() {
        this(DSL.name("ob"), null);
    }

    /**
     * Create an aliased <code>knowledgemap.ob</code> table reference
     */
    public Ob(String alias) {
        this(DSL.name(alias), OB);
    }

    /**
     * Create an aliased <code>knowledgemap.ob</code> table reference
     */
    public Ob(Name alias) {
        this(alias, OB);
    }

    private Ob(Name alias, Table<ObRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ob(Name alias, Table<ObRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Ob(Table<O> child, ForeignKey<O, ObRecord> key) {
        super(child, key, OB);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Knowledgemap.KNOWLEDGEMAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ObRecord, Integer> getIdentity() {
        return Keys.IDENTITY_OB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ObRecord> getPrimaryKey() {
        return Keys.KEY_OB_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ObRecord>> getKeys() {
        return Arrays.<UniqueKey<ObRecord>>asList(Keys.KEY_OB_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ob as(String alias) {
        return new Ob(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ob as(Name alias) {
        return new Ob(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ob rename(String name) {
        return new Ob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ob rename(Name name) {
        return new Ob(name, null);
    }
}
