/*
 * This file is generated by jOOQ.
 */
package com.quick.quickmodel.dao;


import com.quick.quickmodel.dao.tables.Docs;
import com.quick.quickmodel.dao.tables.Knowledge;
import com.quick.quickmodel.dao.tables.Ob;
import com.quick.quickmodel.dao.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Knowledgemap extends SchemaImpl {

    private static final long serialVersionUID = 640314233;

    /**
     * The reference instance of <code>knowledgemap</code>
     */
    public static final Knowledgemap KNOWLEDGEMAP = new Knowledgemap();

    /**
     * The table <code>knowledgemap.docs</code>.
     */
    public final Docs DOCS = com.quick.quickmodel.dao.tables.Docs.DOCS;

    /**
     * The table <code>knowledgemap.knowledge</code>.
     */
    public final Knowledge KNOWLEDGE = com.quick.quickmodel.dao.tables.Knowledge.KNOWLEDGE;

    /**
     * The table <code>knowledgemap.ob</code>.
     */
    public final Ob OB = com.quick.quickmodel.dao.tables.Ob.OB;

    /**
     * The table <code>knowledgemap.user</code>.
     */
    public final User USER = com.quick.quickmodel.dao.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Knowledgemap() {
        super("knowledgemap", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Docs.DOCS,
            Knowledge.KNOWLEDGE,
            Ob.OB,
            User.USER);
    }
}
